name: Run ThreadSanitizer

on:
  push:

jobs:
  run-tsan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: e32c498941d5d92b4695626e805c84802c018038
          submodules: recursive

      - name: Set up Go v1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies and build project (Linux)
        if: runner.os == 'Linux'
        run: | 
          git submodule update --init --recursive
          sudo apt-get update
          sudo apt-get install -y libuuid1 libuv1 libuv1-dev libcups2 libcups2-dev cups-* libmongoc-1.0-0 libmongoc-dev libsnappy-dev libsnappy1v5 libyaml-0-2 libyaml-dev libxen-dev libxen-dev libxencall1 ninja-build generate-ninja libelf-dev libelf1 libprotobuf-dev libprotobuf23 gogoprotobuf libipmimonitoring-dev libipmimonitoring6 libmnl-dev libnetfilter-acct-dev systemd libsystemd0 libsystemd-dev libh2o-dev libbrotli-dev  liblz4-1 liblz4-dev liblz4-tool
          cmake -S . -B build -G "Ninja" && cmake --build build 
          
      - name: Install ThreadSanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Thread Sanitizer (source code) (Linux)
        if: runner.os == 'Linux'
        run: |
            #!/bin/bash
            set +e

            files=$(find . -type f)
            TIMEOUT_DURATION=10

            for file in $files; do
                if [[ "$file" == *.c || "$file" == *.cpp ]]; then
                    include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
                    if ! timeout 60 clang -I "$include_dirs" -fsanitize=thread -fPIE -pie -O2  -g "$file" -o ./compiled.out > /dev/null 2> /tmp/clang_errors.txt; then
                        exit_code=$?
                        if [ $exit_code -eq 1 ]; then
                            continue
                        fi
                        continue 
                    fi

                    timeout $TIMEOUT_DURATION ./compiled.out
                    rm -f ./compiled.out
                fi
            done
